--- !ruby/object:FreeBASE::PluginConfiguration 
name: HelloWorld
version: 1.0
autoload: (true)
require_path: HelloWorld/hello.rb
startup_module: MyFreeRIDELibrary::HelloWorld::MyHelloWorld
start_dependencies: 
  rubyide_gui: "*"
