#### Properties: Core configuration file - Version: 1.0
properties: ~
"|":
  - config: ''
    "|":
      - log_file: "./config/freeride.log"
      - log_level: 2
      - log_name: FreeRIDE
      - plugin_path: "./plugins"
      - product_name: FreeRIDE
      - setup_file: "./config/setup.rb"
  - version: ''
    "|":
      - major: 0
      - minor: 9
      - release: 6
